# GitHub Actions를 이용한 GitHub Pages 자동 배포 워크플로

name: Deploy GitHub Pages site

on:
  # main 브랜치에 push가 일어났을 때 실행됩니다.
  push:
    branches: [ "main" ]

# 워크플로가 한 번에 하나씩만 실행되도록 설정합니다.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # 빌드 잡
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Node.js 20.x.x 버전 사용
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # dist 폴더의 내용물을 업로드합니다.
          path: './dist'
          
  # 배포 잡
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4